language: go
go:
  - 1.5
  - 1.6
  - 1.7
  - tip

sudo: false

script:
  - make setup

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2adb11a0509030479d1b
    on_success: change
    on_failure: always
    on_start: never

