language: go
go:
  - 1.8

sudo: false

script:
  - make all

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2adb11a0509030479d1b
    on_success: change
    on_failure: always
    on_start: never

